import Head from "next/head";

export default function About() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
      </Head>
      <main>
        <div>
          <h1>index page</h1>
        </div>
      </main>
      <footer>
        <div>footer</div>
      </footer>
    </div>
  );
}
